# Generated by Django 5.1 on 2024-08-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="address",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="ph",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="userbio",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="userlink",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="userpronouns",
        ),
    ]
