# Generated by Django 5.1 on 2024-08-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
    ]
