# Generated by Django 5.1 on 2024-08-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0006_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mypost",
            name="username",
        ),
    ]
