# Generated by Django 5.1 on 2024-08-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("userprofile", "0008_delete_mypost"),
    ]

    operations = [
        migrations.CreateModel(
            name="mypost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=400)),
                ("postimage", models.ImageField(upload_to="mypost/")),
            ],
        ),
    ]
