# Generated by Django 5.1 on 2024-08-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creategroup',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
