# Generated by Django 5.1 on 2024-08-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_creategroup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategroup',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
